FROM node:22

WORKDIR /app

# Set npm version
RUN npm install -g npm@10.9.2

COPY package*.json ./
RUN npm install

COPY . .

# Build the production build
RUN npm run build

# Use serve to serve static content
RUN npm install -g serve

# Start the app without running dev mode (production serve)
CMD ["serve", "-s", "dist", "-l", "5173"]
