name: Rebuild Docker Image

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: 'echo "Docker Username is set: ${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin'

      - name: Build and push Docker image
        run: |
          docker build -t johnroselearning/frontend:latest -f Dockerfile.dev .
          docker push johnroselearning/frontend:latest
